### ISSUE TITLE
3.2.2: no setup.py

### ISSUE THREAD

**Issue by kurthindenburg** [jaraco/jaraco.classes#6]
The file from   https://files.pythonhosted.org/packages/source/j/jaraco.classes/jaraco.classes-3.2.2.tar.gz does not have a setup.py.  In macports, we use that to build.  It seems odd that in a 0.0.x upgrade the file would be missing.

**Comment by jaraco** [comment]
The file was removed intentionally in jaraco/skeleton@7e01b721c237ee4947e3b9d6e56bb03a028f3f6a across hundreds of projects. Use of `setup.py` has been discouraged for some time. Instead, packagers are expected to follow PEP 517 for building. Downstream packagers are welcome to restore the `setup.py` boilerplate from that commit in their build tools if needed as a temporary workaround. Implementing a proper PEP 517 builder will be necessary to have support for this package and many others in the Python ecosystem.

>  It seems odd that in a 0.0.x upgrade the file would be missing.

Sorry for that surprise. I realize from some perspective that this change deserved a 1.0 bump (as it's backward-incompatible). From another perspective, the core code itself (the project's API) was unchanged (only generic changes to the packaging were applied). It's that latter perspective that I've adopted when choosing the 0.0.1 bump. If I were to adopt the former perspective, then almost any change would be potentially backward incompatible and would overshadow the value of semver in the core implementation.

Sorry for the inconvenience and thanks for understanding.
