### ISSUE TITLE
README does not contain a project description

### ISSUE THREAD

**Issue by FlorianLudwig** [jaraco/jaraco.classes#7]
Intentionally left blank

**Comment by jaraco** [comment]
The package does contain a description:

https://github.com/jaraco/jaraco.classes/blob/ee34d3535d6169a79878cc35d0a983cdc3970010/setup.cfg#L5

And the readme should link to [the documentation](https://jaracoclasses.readthedocs.io/en/latest/), which provides API docs and examples of what each function does. Between the self-documenting code and the project description, I'm struggling to come up with more detail that would be meaningful.

Oh! The readme _doesn't_ link to the docs. That's a mistake. I'll make sure the badge/link is present.

If you think there's something more that should be provided by the README, feel free to write it or ask the questions that you wish the README would answer.
